name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "build" # location of client code build output
  AADB2C_PROVIDER_CLIENT_ID: ${{ secrets.AADB2C_PROVIDER_CLIENT_ID }}
  AADB2C_PROVIDER_CLIENT_SECRET: ${{ secrets.AADB2C_PROVIDER_CLIENT_SECRET }}

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Replace credentials
        run: |
          CONFIG_FILE="app_location/staticwebapp.config.json"
          if [ -f "$CONFIG_FILE" ]; then
            sed -i "s#TENANT_ID##g" "$CONFIG_FILE"
            sed -i "s#AADB2C_PROVIDER_CLIENT_ID#${AADB2C_PROVIDER_CLIENT_ID}#g" "$CONFIG_FILE"
            sed -i "s#AADB2C_PROVIDER_CLIENT_SECRET#${AADB2C_PROVIDER_CLIENT_SECRET}#g" "$CONFIG_FILE"
          else
            echo "Config file not found: $CONFIG_FILE"
          fi

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_HILL_098B21900 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "app_location" # App source code path (changed from / to reduce package size)
          api_location: ${{ env.API_LOCATION }} # Api source code path - optional
          output_location: ${{ env.APP_ARTIFACT_LOCATION }} # Built app content directory - optional
          skip_app_build: true # Set to true if you are using a pre-built app
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_HILL_098B21900 }}
          action: "close"
